services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI
    volumes:
      - mailhog:/var/lib/mailhog
    restart: unless-stopped

volumes:
  mailhog:
